// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvcvmilogwyrbzbefinm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y3ZtaWxvZ3d5cmJ6YmVmaW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NzUzNDMsImV4cCI6MjA2NDM1MTM0M30.0pl6imWRs2wDvgVZ-dKJbNR3FqZVRrEchfOk-z5G7qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);